services:
  backend: 
    build: ./material-applications/example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=example
      - REQUEST_ORIGIN=http://localhost
    depends_on:
      - redis
      - postgres
    ports: 
      - "8080:8080"
    container_name: backend

  frontend:
    build: 
      context: ./material-applications/example-frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost/api
    depends_on:
      - backend
    ports:
      - "5000:5000"
    container_name: frontend

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: db_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./database:/var/lib/postgresql/data
  
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend